### ISSUE TITLE
topology fail - bolts not emitting correctly

### ISSUE THREAD

**Issue by daTokenizer** [Parsely/streamparse#275] opened 2016-06-21 21:34 UTC
the bug - tuples does not seem to be able to move through bolts - this is braking a previously working code (of course) 

Appeared on both mac and Ubuntu 

minimal code to reproduce:

using the quickstart (which works 100% fine) apply the following changes:
-> add a relay bolt in wordcount.clj

```clj   
 ;; bolt configuration
    {"relay-bolt" (python-bolt-spec
          options
          {"word-spout" :shuffle}
          "bolts.wordcount.Relay"
          ["word"]
          )
    }
    ;; bolt configuration
    {"count-bolt" (python-bolt-spec
          options
          {"relay-bolt" :shuffle}
          "bolts.wordcount.WordCounter"
          ["word" "count"]
          :p 2
          )
    }
```

-> add implementation to that relay bolt in wordcount.py:

```py    
class Relay(Bolt):
    def initialize(self, conf, ctx):
        self.counts = Counter()

    def process(self, tup):
        word = tup.values[0]
        self.log('relay %s'%word)
        self.emit([word])
```

-> sparse run

you will see the words getting to the relay but not to count-bolt.

please advise if this DOES NOT reproduce the bug for you.

**Comment by dan-blanchard** [comment] 2016-06-21 21:51
Counting will not work with a shuffle grouping. You want to group on the `word` field, otherwise your counts will be completely wrong (because you have an independent `Counter` in each `count-bolt` process).

**Comment by daTokenizer** [comment] 2016-06-22 05:24
I don't think you understand - the problem is not that the counters are not working CORRECTLY, but that "count-bolt" never seem to START.

**Comment by adamatan** [comment] 2016-06-22 08:27
Reproduced it on a new EC2 Ubuntu image.

**Comment by dan-blanchard** [comment] 2016-06-22 15:08
Could you please try with the 3.0.0.dev3 release? We're not really addressing issues that are related to the current version and the Clojure topology DSL, because it is replaced entirely by [the Python one](http://streamparse.readthedocs.io/en/master/topologies.html#topology-dsl).  You can install it with `pip install --pre streamparse==3.0.0.dev3`.  We should have a final release of 3.0, and the preview releases are actually quite stable; we've been using them in production for months.

**Comment by daTokenizer** [comment] 2016-06-22 15:34
that's the weird part, I was using it in productions as well.. this new bug was found as a part of a presentation i was preparing.

**Comment by dan-blanchard** [comment] 2016-06-22 15:47
@daTokenizer, the Clojure DSL is only used in streamparse < 3.0, so I'm confused by your comment. If you're already using 3.0.0.dev3, then the file you're editing wouldn't be created by `sparse quickstart`, and would not be used by `sparse run`.

**Comment by daTokenizer** [comment] 2016-06-23 08:02
Sorry @dan-blanchard, when I was saying it I was referencing  my own system (which was of-course running great). As said, this issue was found in preparation of a Streamparse demo.
Currently I am still struggling to start the new Streamparse. Once I'll have it up I'll reply here if I found anything that need taking care of (and close if not).

**Comment by daTokenizer** [comment] 2016-06-23 08:25
findings so far
 
In /usr/local/lib/python2.7/dist-packages/streamparse/util.py", in line 270 
` r'^Storm ([0-9.]+)'` should be  `r'Storm ([0-9.]+)'  ` (the first fails to parse)

In project.clj:
`org.apache.storm/storm-core` is  0.10.0, should be 1.0.1

and then i got this
```
Cleaning from prior builds...
Creating topology Uber-JAR...
Uber-JAR created: /home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar
Removing _resources temporary directory...done
[localhost] local: storm jar /home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmpdj0sHw.yaml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Running: /usr/lib/jvm/java-8-oracle/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/adam/Downloads/apache-storm-1.0.1 -Dstorm.log.dir=/home/adam/Downloads/apache-storm-1.0.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /home/adam/Downloads/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/objenesis-2.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/asm-5.0.3.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar:/home/adam/Downloads/apache-storm-1.0.1/conf:/home/adam/Downloads/apache-storm-1.0.1/bin -Dstorm.jar=/home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmpdj0sHw.yaml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/adam/Downloads/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Parsing file: /tmp/tmpdj0sHw.yaml
406  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
407  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
407  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
Exception in thread "main" Can't construct a java object for tag:yaml.org,2002:org.apache.storm.flux.model.TopologyDef; exception=Cannot create property=name for JavaBean=org.apache.storm.flux.model.TopologyDef@5ed828d; null; Can't construct a java object for tag:yaml.org,2002:python/unicode; exception=Class not found: python/unicode;  in 'string', line 8, column 7:
    name: !!python/unicode 'wordcount'
          ^
 in 'string', line 1, column 1:
    bolts:
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
	at org.apache.storm.flux.parser.FluxParser.loadYaml(FluxParser.java:115)
	at org.apache.storm.flux.parser.FluxParser.parseFile(FluxParser.java:50)
	at org.apache.storm.flux.Flux.runCli(Flux.java:145)
	at org.apache.storm.flux.Flux.main(Flux.java:98)
Caused by: org.yaml.snakeyaml.error.YAMLException: Cannot create property=name for JavaBean=org.apache.storm.flux.model.TopologyDef@5ed828d; null; Can't construct a java object for tag:yaml.org,2002:python/unicode; exception=Class not found: python/unicode;  in 'string', line 8, column 7:
    name: !!python/unicode 'wordcount'
          ^
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	... 9 more
Caused by: Can't construct a java object for tag:yaml.org,2002:python/unicode; exception=Class not found: python/unicode
 in 'string', line 8, column 7:
    name: !!python/unicode 'wordcount'
          ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:296)
	... 11 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: python/unicode
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:633)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	... 13 more

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /home/adam/src/geopy/wordcounter/_build/wordcounter-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmpdj0sHw.yaml'

Aborting.

```

since i don't really know how to approach that please advise to how shold i continue.

thanks.

**Comment by Darkless012** [comment] 2016-06-23 19:58
Seems like duplicate of https://github.com/Parsely/streamparse/issues/240

**Comment by Darkless012** [comment] 2016-06-23 20:00
And the latest error seems like duplicate of https://github.com/Parsely/streamparse/issues/256

**Comment by daTokenizer** [comment] 2016-06-24 11:45
@Darkless012  you are correct about the #240 one... that fixed it.. Good thing we are moving to the python DSL (which is awesome you guys).

About that #256 issue: i'm not using any Unicode..  this is out of the box. yes, I am using python 2.7 but if this is a problem and  it being a quickstart, i think this should be mentioned explicitly. (or have i misunderstood what was the problem?)

**Closed** 2016-07-27 13:31 UTC
Labels: duplicate
