### ISSUE TITLE
Update virtualenv fabric command fail with Fatal error: put() encountered an exception while uploading

### ISSUE THREAD

**Issue by lboudard** [Parsely/streamparse#302] opened 2016-08-23 17:17 UTC
Hi,

I've been encontering some issues deploying on a distant server.
Fatal error: put() encountered an exception while uploading 'virtualenvs/my_topology.txt'

Underlying exception:
    No such file

Aborting.

Fatal error: One or more hosts failed while executing task '_create_or_update_virtualenv'
https://github.com/Parsely/streamparse/blob/master/streamparse/cli/update_virtualenv.py

Seems to be a fabric issue, other reported similar issues, though I couldn't get it working even though not quite same https://github.com/fabric/fabric/issues/1403.
It's weird since I could get it working on some configurations, seems to depends on storm hosts...
I could fix the issue using non mktemp files to push virtualenv files, I'll have a fork with it waiting to have a better solution.

Thanks!

**Comment by dan-blanchard** [comment] 2016-09-01 20:25
Is it possible you were actively editing the requirements file at the moment you were updating the virtualenv? Because I believe the `No such file` exception you're seeing is because your *local* copy of the requirements file doesn't exist, rather than the remote one. It should not matter if the remote file exists or not because we're specify the destination in our `put()` call.  We use `mktemp` simply to make sure that we get a filename that is unique to the nimbus server.

**Comment by lboudard** [comment] 2016-09-29 11:43
@dan-blanchard Nope, it wasn't being edited at the time I tried to submit the application, plus I could fix the issue replacing the tmp path with an absolute path...
https://github.com/artefactory/streamparse/commit/55f14fe15ee1336ba51d96972c29fd25cc32e62e
I haven't investigated this much more but it definitely seems a corner case fabric issue.

**Comment by dan-blanchard** [comment] 2017-06-29 20:17
I'm going to close this as something we can't reproduce. `put()` would not raise an exception if the remote file did not exist, only if the local one didn't.

**Closed by dan-blanchard** 2017-06-29 20:17 UTC
