### ISSUE TITLE
except requests.exceptions.RequestException

### ISSUE THREAD

**Issue by f1-outsourcing** [Parsely/streamparse#186] opened 2015-09-02 18:56 UTC
I have a request method in a spout and do try: and except but still, I am getting these message from storm

java.lang.RuntimeException: subprocess heartbeat timeout
        at backtype.storm.spout.ShellSpout$SpoutHeartbeatTimerTask.run(ShellSpout.java:261) [storm-core-0.9.5.jar:0.9.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_85]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
118761 [pool-51-thread-1] ERROR backtype.storm.daemon.executor -
java.lang.RuntimeException: subprocess heartbeat timeout
        at backtype.storm.spout.ShellSpout$SpoutHeartbeatTimerTask.run(ShellSpout.java:261) [storm-core-0.9.5.jar:0.9.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_85]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_85]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_85]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_85]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

**Comment by dan-blanchard** [comment] 2015-09-02 19:04
This is a duplicate of the inaccurately named #167.  You just need to follow the steps outlined in my [comment there](https://github.com/Parsely/streamparse/issues/167#issuecomment-132304176).

**Closed by dan-blanchard** 2015-09-02 19:04 UTC
