### ISSUE TITLE
Parallelism is not passed when adding via Bolt.spec() and Spout.spec() (3.0.0.dev3)

### ISSUE THREAD

**Issue by rachiebytes** [Parsely/streamparse#269] opened 2016-06-16 14:52 UTC
1. sparse quickstart wordcount (im using storm v1.0.1)
2. in topologies/wordcount.py add parallelism argument to spout and bolt

- WordSpout.spec(par=4)
- WordCountBolt.spec(inputs={word_spout: Grouping.fields('word')}, par=4)

3. sparse run 
4. go check the .yaml file produced, you'll see executers and workers is still set at the default 2
5. sparse run -p 4
6. go check the .yaml file produced and you'll see executers and workers is properly set to 4

**Comment by dan-blanchard** [comment] 2016-06-16 14:55
Thanks for the detailed steps to reproduce!

**Comment by Darkless012** [comment] 2016-06-21 11:09
I might be wrong, but I thought that par=4 in topology definition will multiply number of (in this case python) processes that runs the code.
On the other hand executers and workers are Apache Storm things, that starts the python processes and do the heavy lifting like delivering messages/acking them. So ideally having one worker/acker per "physical" machine in cluster should be the correct value.

**Comment by dan-blanchard** [comment] 2016-06-21 12:09
@Darkless012 is very close, but not quite right.  The whole parallelism thing is documented in some detail [here](http://streamparse.readthedocs.io/en/master/topologies.html#parallelism), but the basic idea is the parallelism hint for a particular component, which for a Python component is the number of Python processes that will run in the topology for that component.  The `-p N` flag sets the number of workers and ackers, which is basically the number of JVM processes that Storm will use for the entire topology.  

These are different things, and you should set `-p` to the number of machines in your cluster, like @Darkless012 said.

I apologize for quickly misreading the issue the first time, but I'm closing this since it's just a misunderstanding.

**Closed by dan-blanchard** 2016-06-21 12:09 UTC
