### ISSUE TITLE
Error running wordcount

### ISSUE THREAD

**Issue by mverrilli** [Parsely/streamparse#251] opened 2016-05-11 20:30 UTC
I brand new with this... sorry iI missed a step.  I'm running this on Solaris, so there might be some environmental difference going on here.

I run sparse run in the wordcount directory.  

```
#sparse run
Running wordcount topology...
Routing Python logging to /mypath/wordcount/logs.
Running lein command to run local cluster:
lein run -m streamparse.commands.run/-main topologies/wordcount.clj -t 0 --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'streamparse.log.path="/mypath/wordcount/logs"' --option 'streamparse.log.level="debug"'
```

This is the first error thread I see. 

```
21703 [Thread-25] ERROR backtype.storm.task.ShellBolt - Halting process: ShellBolt died.
java.lang.RuntimeException: backtype.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:
Traceback (most recent call last):
  File "/mypath/python/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/mypath/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mypath/python/lib/python2.7/site-packages/streamparse/run.py", line 25, in <module>
    main()
  File "/mypath/python/lib/python2.7/site-packages/streamparse/run.py", line 21, in main
    cls().run()
  File "/mypath/python/lib/python2.7/site-packages/streamparse/storm/component.py", line 484, in run
    self._setup_component(storm_conf, context)
  File "/mypath/python/lib/python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
  File "/mypath/python/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/mypath/python/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/mypath/python/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/mypath/python/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/var/tmp/6fb789eb-9b88-488b-a4fd-b546bb8cc5c1/supervisor/stormdist/wordcount-1-1462997450/resources/"/mypath/wordcount/logs"/streamparse_wordcount_count-bolt_4_14774.log'


        at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:101) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:318) ~[storm-core-0.9.5.jar:0.9.5]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

Am I doing something wrong?

**Comment by mverrilli** [comment] 2016-05-12 18:16
I don't understand the reference to `.../resources/"/mypath/wordcount/logs"`  Is this normal or did something get messed up with how it derives the path name? Since I've never used this before, maybe that's normal, but it doesn't seem normal to me. 

`[Errno 2] No such file or directory: u'/var/tmp/6fb789eb-9b88-488b-a4fd-b546bb8cc5c1/supervisor/stormdist/wordcount-1-1462997450/resources/"/mypath/wordcount/logs"/streamparse_wordcount_count-bolt_4_14774.log`

**Comment by mverrilli** [comment] 2016-05-12 19:44
Ok, I've made progress, sort of. When I execute the lein command manually but remove the double-quotes, it works. Somehow either streamparse is added in double-quotes, or my environment is not translating them properly. 

`lein run -m streamparse.commands.run/-main topologies/wordcount.clj -t 0 --option 'topology.workers=2' --option 'topology.acker.executors=2' --option **'streamparse.log.path=/mypath/wordcount/logs'** --option 'streamparse.log.level="debug"'`

**Comment by dan-blanchard** [comment] 2016-05-19 18:21
Thanks for your detailed reporting.  This is unlikely to be an issue in the future, since we no longer need to rely on Clojure code in streamparse 3.0 (which you can test by running `pip install --pre streamparse==3.0.0.dev3`), but I'll definitely double-check before we release the final version of 3.0.

**Comment by dan-blanchard** [comment] 2016-06-02 20:29
Closing this as a duplicate of #214.

**Closed by dan-blanchard** 2016-06-02 20:29 UTC
