### ISSUE TITLE
How to balance work load for the bolt evenly across all machines in the cluster?

### ISSUE THREAD

**Issue by kateabbasi** [Parsely/streamparse#307] opened 2016-08-30 21:13 UTC
We have two machines in the cluster. Our topology has three bolts. Each bolt has two executors, one per machine; however, only one machine is busy doing work for the bolt. How can we ensure that the work load for each bolt is spread evenly across all the machines? I have attached a screenshot from Storm UI showing Executors for one of our bolts.
![screen shot 2016-08-30 at 5 07 10 pm](https://cloud.githubusercontent.com/assets/10709195/18107039/4007d2e2-6ed4-11e6-8e31-d3fdee00a1db.png)

**Comment by HeartSaVioR** [comment] 2016-08-30 23:08
You're encouraged to post a question regarding Apache Storm itself (not StreamParse) to Apache Storm user@ mailing list.
Please refer http://storm.apache.org/getting-help.html

**Comment by mattsgithub** [comment] 2016-08-31 13:55
How can we be absolutely certain that the problem is not StreamParse? We are observing this behavior in our Python deployments (using streamparse) but not in our pure Java deployments. Has anyone encountered this issue?

**Comment by dan-blanchard** [comment] 2016-08-31 14:02
Could you please post your topology files and the command you're using to submit them?

**Comment by HeartSaVioR** [comment] 2016-08-31 14:14
Yeah I agree I was hasty on this. Normally the grouping which component uses for upstream is key point for work load skew, which is general question/issue for Apache Storm. 
Anyway it would be better to see topology files to have a look deeply.

**Comment by kateabbasi** [comment] 2016-08-31 15:09
Thank you for looking into this. Below is the command we use to submit topology:

`sparse submit --environment "dev" --name "carbon" -fu`

I have attached zip file containing topology file, project.clj and config.json
[Archive.zip](https://github.com/Parsely/streamparse/files/447573/Archive.zip)

We use streamparse 3.0.1, but have observed the same issue with previous version as well.

**Comment by dan-blanchard** [comment] 2016-08-31 15:46
Thanks for the files.  I'm going to paste relevant bits here in case someone looks at this in the future and the link is dead.

Topology:

```py
class CarbonTopology(Topology):
    carbon_spout = KafkaSpout.spec() 
    augmentor_bolt = DBAugmentorBolt.spec(inputs=[carbon_spout], par=2) 
    ingestor_bolt = IngestorBolt.spec(inputs=[augmentor_bolt], par=2) 
    store_bolt = MongoStoreBolt.spec(inputs=[ingestor_bolt], par=2) 
```

Config:
```json
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "envs": {
        "dev": {
           "use_ssh_for_nimbus": false,
           "use_virtualenv": false,
           "user": "test",
           "nimbus": "localhost",
           "workers": [
                "ip-10-120-1-35",
                "ip-10-120-3-113"
            ],
            "log": {
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "error"
            },
            "options":{
              "topology.max.spout.pending": 25,
                "kafka.hosts":"xxxx:9092",
                "kafka.topic":"test",
                "kafka.consumer_group_name":"scoring_pyconsumer"
                
            }
        }
    }
}
```

Interestingly, since you've not specified any grouping, you're using a shuffle grouping which *should* distribute things between the two downstream components pretty evenly.  We're using shuffle groupings all over the place and seeing a pretty even load distribution.  The only time we've seen that not be the case is when some tuples take a lot longer to process than others, but that doesn't seem to be the case from your screenshot.

**Comment by kateabbasi** [comment] 2016-08-31 17:32
Some more information...


![screen shot 2016-08-31 at 1 22 11 pm](https://cloud.githubusercontent.com/assets/10709195/18139126/0857edf0-6f7e-11e6-8ffe-1550335b0f9a.png)

We have two worker machines: .113 and .35. What we are observing is that execution for each component is isolated to one machine rather than spread out between the two machines. Another interesting observation is that components are spread out evenly (2 for each machine). That is all work for 
carbon_spout is done on .113
augmentor_bolt on .35
ingestor_bolt on .113
store_bolt on .35

**Comment by Purushotham233** [comment] 2017-06-05 13:20
Facing similar issue. Any update?

**Comment by dan-blanchard** [comment] 2017-06-29 20:20
Seeing as we regularly successfully use shuffle groupings with `streamparse` to evenly spread load out among a cluster of 20 nodes, I'm going to close this issue and refer people to the Apache Storm mailing list for help with such issues.

**Closed by dan-blanchard** 2017-06-29 20:20 UTC
