### ISSUE TITLE
Mac comptability 'run arg' - sparse 2.1.3

### ISSUE THREAD

**Issue by lnxg33k** [Parsely/streamparse#214] opened 2015-12-22 19:13 UTC
I am trying to run streamparse locally through run argument in a virtualenv.

```
(testme)❰lnxg33k❙~/testme/wordcount❱✔≻ sparse --version
sparse 2.1.3
(testme)❰lnxg33k❙~/testme/wordcount❱✔≻ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
(testme)❰lnxg33k❙~/testme/wordcount❱✔≻ lein version
Leiningen 2.5.3 on Java 1.8.0_51 Java HotSpot(TM) 64-Bit Server VM
```

But I came through that error:
```
4605 [Thread-25] ERROR backtype.storm.task.ShellBolt - Halting process: ShellBolt died.
java.lang.RuntimeException: backtype.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 25, in <module>
    main()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 21, in main
    cls().run()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 484, in run
    self._setup_component(storm_conf, context)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/private/var/folders/cn/nx96yv610yq8thfjb_fg1kfm0000gn/T/53069658-443e-42eb-a749-eca60a359450/supervisor/stormdist/wordcount-1-1450811460/resources/"/Users/lnxg33k/testme/wordcount/logs"/streamparse_wordcount_count-bolt_4_59063.log'


	at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:101) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:318) ~[storm-core-0.9.5.jar:0.9.5]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
4605 [Thread-16-word-spout] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: pid:59062, name:word-spout exitCode:-1, errorString:Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 25, in <module>
    main()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 21, in main
    cls().run()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 484, in run
    self._setup_component(storm_conf, context)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/private/var/folders/cn/nx96yv610yq8thfjb_fg1kfm0000gn/T/6122b579-4183-4d86-9876-bfb802fd8a1f/supervisor/stormdist/wordcount-1-1450811460/resources/"/Users/lnxg33k/testme/wordcount/logs"/streamparse_wordcount_word-spout_5_59062.log'

	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:180) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:91) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.daemon.executor$fn__3371$fn__3386$fn__3415.invoke(executor.clj:565) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~[storm-core-0.9.5.jar:0.9.5]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_51]
	at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_51]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_51]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_51]
	at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_51]
	at backtype.storm.multilang.JsonSerializer.writeString(JsonSerializer.java:96) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.multilang.JsonSerializer.writeMessage(JsonSerializer.java:89) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.multilang.JsonSerializer.writeSpoutMsg(JsonSerializer.java:81) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.utils.ShellProcess.writeSpoutMsg(ShellProcess.java:112) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:142) ~[storm-core-0.9.5.jar:0.9.5]
	... 5 common frames omitted
4605 [Thread-25] ERROR backtype.storm.daemon.executor -
java.lang.RuntimeException: backtype.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 25, in <module>
    main()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 21, in main
    cls().run()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 484, in run
    self._setup_component(storm_conf, context)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/private/var/folders/cn/nx96yv610yq8thfjb_fg1kfm0000gn/T/53069658-443e-42eb-a749-eca60a359450/supervisor/stormdist/wordcount-1-1450811460/resources/"/Users/lnxg33k/testme/wordcount/logs"/streamparse_wordcount_count-bolt_4_59063.log'


	at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:101) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:318) ~[storm-core-0.9.5.jar:0.9.5]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
4606 [Thread-16-word-spout] ERROR backtype.storm.daemon.executor -
java.lang.RuntimeException: pid:59062, name:word-spout exitCode:-1, errorString:Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 25, in <module>
    main()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/run.py", line 21, in main
    cls().run()
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 484, in run
    self._setup_component(storm_conf, context)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: u'/private/var/folders/cn/nx96yv610yq8thfjb_fg1kfm0000gn/T/6122b579-4183-4d86-9876-bfb802fd8a1f/supervisor/stormdist/wordcount-1-1450811460/resources/"/Users/lnxg33k/testme/wordcount/logs"/streamparse_wordcount_word-spout_5_59062.log'

	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:180) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:91) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.daemon.executor$fn__3371$fn__3386$fn__3415.invoke(executor.clj:565) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~[storm-core-0.9.5.jar:0.9.5]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method) ~[na:1.8.0_51]
	at java.io.FileOutputStream.write(FileOutputStream.java:326) ~[na:1.8.0_51]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_51]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_51]
	at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_51]
	at backtype.storm.multilang.JsonSerializer.writeString(JsonSerializer.java:96) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.multilang.JsonSerializer.writeMessage(JsonSerializer.java:89) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.multilang.JsonSerializer.writeSpoutMsg(JsonSerializer.java:81) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.utils.ShellProcess.writeSpoutMsg(ShellProcess.java:112) ~[storm-core-0.9.5.jar:0.9.5]
	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:142) ~[storm-core-0.9.5.jar:0.9.5]
	... 5 common frames omitted
4607 [Thread-11-__acker] INFO  backtype.storm.daemon.executor - Preparing bolt __acker:(2)
4607 [Thread-11-__acker] INFO  backtype.storm.daemon.executor - Prepared bolt __acker:(2)
4609 [ProcessThread(sid:0 cport:-1):] INFO  org.apache.storm.zookeeper.server.PrepRequestProcessor - Got user-level KeeperException when processing sessionid:0x151cb1a05a0000d type:create cxid:0x25 zxid:0x26 txntype:-1 reqpath:n/a Error Path:/storm/errors/wordcount-1-1450811460 Error:KeeperErrorCode = NodeExists for /storm/errors/wordcount-1-1450811460
4610 [Thread-12-count-bolt] INFO  backtype.storm.daemon.executor - Preparing bolt count-bolt:(3)
4611 [Thread-12-count-bolt] INFO  backtype.storm.utils.ShellProcess - Storm multilang serializer: backtype.storm.multilang.JsonSerializer
Traceback (most recent call last):
  File "/Users/lnxg33k/testme/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 57, in main
    args.func(args)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/cli/run.py", line 81, in main
    debug=args.debug)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/streamparse/cli/run.py", line 52, in run_local_topology
    run(full_cmd)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/invoke/__init__.py", line 23, in run
    return Context().run(command, **kwargs)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/Users/lnxg33k/testme/lib/python2.7/site-packages/invoke/runners.py", line 284, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!

Exit code: 11
```

That also happened when I tried a global install and not a virtenv.

**Comment by dan-blanchard** [comment] 2015-12-22 19:22
Can you paste your `config.json`? It looks like it might be an error there, since it's a path issue with trying to find your log file:

```
 No such file or directory: u'/private/var/folders/cn/nx96yv610yq8thfjb_fg1kfm0000gn/T/53069658-443e-42eb-a749-eca60a359450/supervisor/stormdist/wordcount-1-1450811460/resources/"/Users/lnxg33k/testme/wordcount/logs"/streamparse_wordcount_count-bolt_4_59063.log'
```

**Comment by lnxg33k** [comment] 2015-12-22 19:27
@dan-blanchard I did not update the config file as I was running a quick test and I think there is a default val for it which is cwd+logs/

```
(testme)❰lnxg33k❙~/testme/wordcount❱✔≻ cat config.json
{
    "library": "",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "",
            "nimbus": "",
            "workers": [],
            "log": {
                "path": "",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "virtualenv_root": ""
        }
    }
}
```

**Comment by pramukta** [comment] 2015-12-28 21:41
I think this is another instance of the quoting issue that results in #215 as well.

**Comment by dan-blanchard** [comment] 2016-03-15 17:44
I use a Mac and I can't reproduce this issue on master or on the 3.0 developer preview, so I'm closing this.

**Closed by dan-blanchard** 2016-03-15 17:44 UTC
