### ISSUE TITLE
Update docs: Storm is required with streamparse 3.0+

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#253] opened 2016-05-12 12:53 UTC
sparse quickstart wordcount

    sparse run

Warning: local() encountered an error (return code 127) while executing 'storm version'

Traceback (most recent call last):
  File "/home/darkless/.virtualenvs/sparse3/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 85, in main
    debug=args.debug)
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 31, in run_local_topology
    local_version = local_storm_version()
  File "/home/darkless/.virtualenvs/sparse3/local/lib/python2.7/site-packages/streamparse/util.py", line 268, in local_storm_version
    res.stderr))
RuntimeError: Unable to run 'storm version'!
STDOUT:

STDERR:
/bin/sh: 1: storm: not found

    sparse --version
    sparse 3.0.0.dev3

**Comment by dan-blanchard** [comment] 2016-05-12 12:58
Yeah, Storm is required to be installed on your local machine with 3.0.

**Comment by dan-blanchard** [comment] 2016-05-12 13:03
I just realized I never updated the quickstart docs to say that.  Should definitely do that.

**Comment by Darkless012** [comment] 2016-05-12 13:05
Thanks, after I manage to run cluster locally on Storm 1.0.0 I will try update quickstart doc. At least you will know the "view" from an outsider.

**Comment by Darkless012** [comment] 2016-05-18 08:44
https://github.com/Parsely/streamparse/pull/261 Should contain info about Storm.

Is Lein still needed?

**Comment by dan-blanchard** [comment] 2016-06-02 20:15
Fixed in #261.

**Closed by dan-blanchard** 2016-06-02 20:15 UTC
Labels: documentation, help wanted

**Comment by trebsirk** [comment] 2016-08-02 18:41
I was getting the same error on Ubuntu following https://github.com/traderres/webClass/blob/master/learnPythonStreamParse/howToInstallStreamParseOnCentos.txt. 
Centos puts Anaconda in ~/anaconda,  so I copied that into /opt/anaconda. Also had to copy storm into /opt/storm. Then updated the path in ~/.bashrc. 
So I don't get the error mentioned above anymore. I'm getting this error now:

Error: Could not find or load main class org.apache.storm.flux.Flux

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /home/kris/Documents/python/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmpmIocCh.yaml'

**Comment by amontalenti** [comment] 2016-08-03 07:43
@trebsirk Your issue now reduces to a dupe of #295. Take a look there for a resolution.
