### ISSUE TITLE
ERROR : Required field 'nimbus_uptime_secs' is unset!

### ISSUE THREAD

**Issue by hakrnirmal** [Parsely/streamparse#279] opened 2016-07-25 05:11 UTC
I am trying to run storm topology in production mode,

**Version:**
Streamparse - 2.1.4
Python - 2.7.8
Storm 0.10.0 

**project.clj**
(defproject meta "0.0.1-SNAPSHOT"
  :source-paths ["topologies"]
  :resource-paths ["_resources"]
  :target-path "_build"
  :min-lein-version "2.0.0"
  :jvm-opts ["-client"]
  :dependencies  [[org.apache.storm/storm-core "0.10.0"]
                  [com.parsely/streamparse "0.0.4-SNAPSHOT"]
                  ]
  :jar-exclusions     [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  :uberjar-exclusions [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  )

**config.json**
{
    "library": "",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "ram",
            "nimbus": "10.218.173.100",
            "workers": ["10.154.9.166"],
            "log": {
                "path": "/home/ram/log/storm/streamparse",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "use_ssh_for_nimbus": true,
            "use_virtualenv": false,
            "virtualenv_root": "/home/ram/storm-topologies/meta"
        }
    }
}

When submitting topology as, **sparse submit**
getting,

java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: **Required field 'nimbus_uptime_secs' is unset!** Struct:ClusterSummary(supervisors:[SupervisorSummary(host:10.154.9.166, uptime_secs:1654461, num_workers:2, num_used_workers:0, supervisor_id:0a07f441-05f8-4103-b439-22cf42a1fcff, version:0.10.0.2.4.2.0-258)], nimbus_uptime_secs:0, topologies:[])

**Comment by amontalenti** [comment] 2016-07-25 14:31
I think this is a dupe of #202 and an upstream issue covered in apache/storm#868.

**Comment by dan-blanchard** [comment] 2016-07-26 15:51
Agreed. Closing as duplicate.

**Closed by dan-blanchard** 2016-07-26 15:51 UTC
