### ISSUE TITLE
sparse producing invalid syntax error

### ISSUE THREAD

**Issue by matthayes** [Parsely/streamparse#170] opened 2015-08-20 20:30 UTC
I ran `sparse` and got the error below.  Is Python 3.4 not supported?

```
File "/Users/mhayes/.pyenv/versions/3.4.2/lib/python3.4/site-packages/fabric/context_managers.py", line 535
    def accept(channel, (src_addr, src_port), (dest_addr, dest_port)):

SyntaxError: invalid syntax
```

**Comment by dan-blanchard** [comment] 2015-08-20 20:39
You just need to install the Python 3 compatible fork of fabric listed in our [requirements.txt](https://github.com/Parsely/streamparse/blob/master/requirements.txt).  This is a duplicate of #76.  

Some day we will get rid of fabric and this won't be an issue.

**Closed by dan-blanchard** 2015-08-20 20:39 UTC

**Comment by matthayes** [comment] 2015-08-20 21:36
Got it, that worked.  Thanks!
